name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: educandu/mongo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag from build environment
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
        id: tag
      - name: Build and push
        uses: dawidd6/action-docker-publish-changed@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          platforms: linux/amd64,linux/arm64,linux/arm
          tag: ${{ steps.tag.outputs.tag }}
